name: 'Networks & Wireless'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E8E0E0'
    - '#985048'
    - '#707080'
    - '#60A8C8'
    - '#F0E8D0'
  brandStrength: 0.515203
  lightness: 0.53125
  saturation: 0.546453
  rhythmicContrast: 0.5
purpose: []
