analytics: {}
color:
  brandColors:
    - '#E8E0E0'
    - '#985048'
    - '#707080'
    - '#60A8C8'
    - '#F0E8D0'
  brandStrength: 0.515203
  lightness: 0.53125
  rhythmicContrast: 0.723818
  saturation: 0.546453
cta: {}
layout_spectrum: 1
name: 'Networks & Wireless'
opengraph: {}
purpose: []
typography_spectrum: 0.805743
