analytics: {}
color:
  brandColors:
    - '#90B090'
    - '#000000'
    - '#709878'
    - '#000000'
    - '#000000'
  brandStrength: 0.910473
  lightness: 0.53125
  rhythmicContrast: 0.913354
  saturation: 0.765203
cta: {}
layout_spectrum: 1
name: 'Networks & Wireless'
opengraph: {}
purpose: []
typography_spectrum: 0.805743
